// Referenz-Metadaten der 114 Suren: Nummer, transliterierter Name, Ayah-Anzahl
// (Hafs-Zählung). Dies sind Fakten/Metadaten – KEIN Qur'an-Text. Der eigentliche
// Mushaf-Text/Übersetzung/Audio wird laut docs/INTEGRATIONS.md später über
// lizenzierte Provider eingebunden.
export const SURAHS = [
  { n: 1, name: 'Al-Fatihah', ayat: 7 },
  { n: 2, name: 'Al-Baqarah', ayat: 286 },
  { n: 3, name: "Ali 'Imran", ayat: 200 },
  { n: 4, name: 'An-Nisa', ayat: 176 },
  { n: 5, name: "Al-Ma'idah", ayat: 120 },
  { n: 6, name: "Al-An'am", ayat: 165 },
  { n: 7, name: "Al-A'raf", ayat: 206 },
  { n: 8, name: 'Al-Anfal', ayat: 75 },
  { n: 9, name: 'At-Tawbah', ayat: 129 },
  { n: 10, name: 'Yunus', ayat: 109 },
  { n: 11, name: 'Hud', ayat: 123 },
  { n: 12, name: 'Yusuf', ayat: 111 },
  { n: 13, name: "Ar-Ra'd", ayat: 43 },
  { n: 14, name: 'Ibrahim', ayat: 52 },
  { n: 15, name: 'Al-Hijr', ayat: 99 },
  { n: 16, name: 'An-Nahl', ayat: 128 },
  { n: 17, name: 'Al-Isra', ayat: 111 },
  { n: 18, name: 'Al-Kahf', ayat: 110 },
  { n: 19, name: 'Maryam', ayat: 98 },
  { n: 20, name: 'Ta-Ha', ayat: 135 },
  { n: 21, name: 'Al-Anbiya', ayat: 112 },
  { n: 22, name: 'Al-Hajj', ayat: 78 },
  { n: 23, name: "Al-Mu'minun", ayat: 118 },
  { n: 24, name: 'An-Nur', ayat: 64 },
  { n: 25, name: 'Al-Furqan', ayat: 77 },
  { n: 26, name: "Ash-Shu'ara", ayat: 227 },
  { n: 27, name: 'An-Naml', ayat: 93 },
  { n: 28, name: 'Al-Qasas', ayat: 88 },
  { n: 29, name: "Al-'Ankabut", ayat: 69 },
  { n: 30, name: 'Ar-Rum', ayat: 60 },
  { n: 31, name: 'Luqman', ayat: 34 },
  { n: 32, name: 'As-Sajdah', ayat: 30 },
  { n: 33, name: 'Al-Ahzab', ayat: 73 },
  { n: 34, name: 'Saba', ayat: 54 },
  { n: 35, name: 'Fatir', ayat: 45 },
  { n: 36, name: 'Ya-Sin', ayat: 83 },
  { n: 37, name: 'As-Saffat', ayat: 182 },
  { n: 38, name: 'Sad', ayat: 88 },
  { n: 39, name: 'Az-Zumar', ayat: 75 },
  { n: 40, name: 'Ghafir', ayat: 85 },
  { n: 41, name: 'Fussilat', ayat: 54 },
  { n: 42, name: 'Ash-Shura', ayat: 53 },
  { n: 43, name: 'Az-Zukhruf', ayat: 89 },
  { n: 44, name: 'Ad-Dukhan', ayat: 59 },
  { n: 45, name: 'Al-Jathiyah', ayat: 37 },
  { n: 46, name: 'Al-Ahqaf', ayat: 35 },
  { n: 47, name: 'Muhammad', ayat: 38 },
  { n: 48, name: 'Al-Fath', ayat: 29 },
  { n: 49, name: 'Al-Hujurat', ayat: 18 },
  { n: 50, name: 'Qaf', ayat: 45 },
  { n: 51, name: 'Adh-Dhariyat', ayat: 60 },
  { n: 52, name: 'At-Tur', ayat: 49 },
  { n: 53, name: 'An-Najm', ayat: 62 },
  { n: 54, name: 'Al-Qamar', ayat: 55 },
  { n: 55, name: 'Ar-Rahman', ayat: 78 },
  { n: 56, name: "Al-Waqi'ah", ayat: 96 },
  { n: 57, name: 'Al-Hadid', ayat: 29 },
  { n: 58, name: 'Al-Mujadila', ayat: 22 },
  { n: 59, name: 'Al-Hashr', ayat: 24 },
  { n: 60, name: 'Al-Mumtahanah', ayat: 13 },
  { n: 61, name: 'As-Saff', ayat: 14 },
  { n: 62, name: "Al-Jumu'ah", ayat: 11 },
  { n: 63, name: 'Al-Munafiqun', ayat: 11 },
  { n: 64, name: 'At-Taghabun', ayat: 18 },
  { n: 65, name: 'At-Talaq', ayat: 12 },
  { n: 66, name: 'At-Tahrim', ayat: 12 },
  { n: 67, name: 'Al-Mulk', ayat: 30 },
  { n: 68, name: 'Al-Qalam', ayat: 52 },
  { n: 69, name: 'Al-Haqqah', ayat: 52 },
  { n: 70, name: "Al-Ma'arij", ayat: 44 },
  { n: 71, name: 'Nuh', ayat: 28 },
  { n: 72, name: 'Al-Jinn', ayat: 28 },
  { n: 73, name: 'Al-Muzzammil', ayat: 20 },
  { n: 74, name: 'Al-Muddaththir', ayat: 56 },
  { n: 75, name: 'Al-Qiyamah', ayat: 40 },
  { n: 76, name: 'Al-Insan', ayat: 31 },
  { n: 77, name: 'Al-Mursalat', ayat: 50 },
  { n: 78, name: 'An-Naba', ayat: 40 },
  { n: 79, name: "An-Nazi'at", ayat: 46 },
  { n: 80, name: "'Abasa", ayat: 42 },
  { n: 81, name: 'At-Takwir', ayat: 29 },
  { n: 82, name: 'Al-Infitar', ayat: 19 },
  { n: 83, name: 'Al-Mutaffifin', ayat: 36 },
  { n: 84, name: 'Al-Inshiqaq', ayat: 25 },
  { n: 85, name: 'Al-Buruj', ayat: 22 },
  { n: 86, name: 'At-Tariq', ayat: 17 },
  { n: 87, name: "Al-A'la", ayat: 19 },
  { n: 88, name: 'Al-Ghashiyah', ayat: 26 },
  { n: 89, name: 'Al-Fajr', ayat: 30 },
  { n: 90, name: 'Al-Balad', ayat: 20 },
  { n: 91, name: 'Ash-Shams', ayat: 15 },
  { n: 92, name: 'Al-Layl', ayat: 21 },
  { n: 93, name: 'Ad-Duha', ayat: 11 },
  { n: 94, name: 'Ash-Sharh', ayat: 8 },
  { n: 95, name: 'At-Tin', ayat: 8 },
  { n: 96, name: "Al-'Alaq", ayat: 19 },
  { n: 97, name: 'Al-Qadr', ayat: 5 },
  { n: 98, name: 'Al-Bayyinah', ayat: 8 },
  { n: 99, name: 'Az-Zalzalah', ayat: 8 },
  { n: 100, name: "Al-'Adiyat", ayat: 11 },
  { n: 101, name: "Al-Qari'ah", ayat: 11 },
  { n: 102, name: 'At-Takathur', ayat: 8 },
  { n: 103, name: "Al-'Asr", ayat: 3 },
  { n: 104, name: 'Al-Humazah', ayat: 9 },
  { n: 105, name: 'Al-Fil', ayat: 5 },
  { n: 106, name: 'Quraysh', ayat: 4 },
  { n: 107, name: "Al-Ma'un", ayat: 7 },
  { n: 108, name: 'Al-Kawthar', ayat: 3 },
  { n: 109, name: 'Al-Kafirun', ayat: 6 },
  { n: 110, name: 'An-Nasr', ayat: 3 },
  { n: 111, name: 'Al-Masad', ayat: 5 },
  { n: 112, name: 'Al-Ikhlas', ayat: 4 },
  { n: 113, name: 'Al-Falaq', ayat: 5 },
  { n: 114, name: 'An-Nas', ayat: 6 },
];

export const surahByN = (n) => SURAHS.find((s) => s.n === Number(n)) || null;

// Anzahl Ayat in einem (Surah:Ayah)-Bereich (inklusive), auch über Surengrenzen.
export function ayahSpan(surahFrom, ayahFrom, surahTo, ayahTo) {
  const sf = Number(surahFrom);
  const st = Number(surahTo);
  const af = Number(ayahFrom);
  const at = Number(ayahTo);
  if (!surahByN(sf) || !surahByN(st)) return 0;
  if (sf > st || (sf === st && af > at)) return 0;
  if (sf === st) return at - af + 1;
  let total = surahByN(sf).ayat - af + 1; // Rest der Startsure
  for (let n = sf + 1; n < st; n++) total += surahByN(n).ayat; // volle Suren dazwischen
  total += at; // bis Ziel-Ayah in der Endsure
  return total;
}
