// Referenz-Metadaten der 114 Suren: Nummer, transliterierter Name, Ayah-Anzahl
// (Hafs-Zählung). Dies sind Fakten/Metadaten – KEIN Qur'an-Text. Der eigentliche
// Mushaf-Text/Übersetzung/Audio wird laut docs/INTEGRATIONS.md später über
// lizenzierte Provider eingebunden.
export const SURAHS = [
  { n: 1, name: 'Al-Fatihah', ayat: 7, ar: 'الفاتحة' },
  { n: 2, name: 'Al-Baqarah', ayat: 286, ar: 'البقرة' },
  { n: 3, name: "Ali 'Imran", ayat: 200, ar: 'آل عمران' },
  { n: 4, name: 'An-Nisa', ayat: 176, ar: 'النساء' },
  { n: 5, name: "Al-Ma'idah", ayat: 120, ar: 'المائدة' },
  { n: 6, name: "Al-An'am", ayat: 165, ar: 'الأنعام' },
  { n: 7, name: "Al-A'raf", ayat: 206, ar: 'الأعراف' },
  { n: 8, name: 'Al-Anfal', ayat: 75, ar: 'الأنفال' },
  { n: 9, name: 'At-Tawbah', ayat: 129, ar: 'التوبة' },
  { n: 10, name: 'Yunus', ayat: 109, ar: 'يونس' },
  { n: 11, name: 'Hud', ayat: 123, ar: 'هود' },
  { n: 12, name: 'Yusuf', ayat: 111, ar: 'يوسف' },
  { n: 13, name: "Ar-Ra'd", ayat: 43, ar: 'الرعد' },
  { n: 14, name: 'Ibrahim', ayat: 52, ar: 'ابراهيم' },
  { n: 15, name: 'Al-Hijr', ayat: 99, ar: 'الحجر' },
  { n: 16, name: 'An-Nahl', ayat: 128, ar: 'النحل' },
  { n: 17, name: 'Al-Isra', ayat: 111, ar: 'الإسراء' },
  { n: 18, name: 'Al-Kahf', ayat: 110, ar: 'الكهف' },
  { n: 19, name: 'Maryam', ayat: 98, ar: 'مريم' },
  { n: 20, name: 'Ta-Ha', ayat: 135, ar: 'طه' },
  { n: 21, name: 'Al-Anbiya', ayat: 112, ar: 'الأنبياء' },
  { n: 22, name: 'Al-Hajj', ayat: 78, ar: 'الحج' },
  { n: 23, name: "Al-Mu'minun", ayat: 118, ar: 'المؤمنون' },
  { n: 24, name: 'An-Nur', ayat: 64, ar: 'النور' },
  { n: 25, name: 'Al-Furqan', ayat: 77, ar: 'الفرقان' },
  { n: 26, name: "Ash-Shu'ara", ayat: 227, ar: 'الشعراء' },
  { n: 27, name: 'An-Naml', ayat: 93, ar: 'النمل' },
  { n: 28, name: 'Al-Qasas', ayat: 88, ar: 'القصص' },
  { n: 29, name: "Al-'Ankabut", ayat: 69, ar: 'العنكبوت' },
  { n: 30, name: 'Ar-Rum', ayat: 60, ar: 'الروم' },
  { n: 31, name: 'Luqman', ayat: 34, ar: 'لقمان' },
  { n: 32, name: 'As-Sajdah', ayat: 30, ar: 'السجدة' },
  { n: 33, name: 'Al-Ahzab', ayat: 73, ar: 'الأحزاب' },
  { n: 34, name: 'Saba', ayat: 54, ar: 'سبإ' },
  { n: 35, name: 'Fatir', ayat: 45, ar: 'فاطر' },
  { n: 36, name: 'Ya-Sin', ayat: 83, ar: 'يس' },
  { n: 37, name: 'As-Saffat', ayat: 182, ar: 'الصافات' },
  { n: 38, name: 'Sad', ayat: 88, ar: 'ص' },
  { n: 39, name: 'Az-Zumar', ayat: 75, ar: 'الزمر' },
  { n: 40, name: 'Ghafir', ayat: 85, ar: 'غافر' },
  { n: 41, name: 'Fussilat', ayat: 54, ar: 'فصلت' },
  { n: 42, name: 'Ash-Shura', ayat: 53, ar: 'الشورى' },
  { n: 43, name: 'Az-Zukhruf', ayat: 89, ar: 'الزخرف' },
  { n: 44, name: 'Ad-Dukhan', ayat: 59, ar: 'الدخان' },
  { n: 45, name: 'Al-Jathiyah', ayat: 37, ar: 'الجاثية' },
  { n: 46, name: 'Al-Ahqaf', ayat: 35, ar: 'الأحقاف' },
  { n: 47, name: 'Muhammad', ayat: 38, ar: 'محمد' },
  { n: 48, name: 'Al-Fath', ayat: 29, ar: 'الفتح' },
  { n: 49, name: 'Al-Hujurat', ayat: 18, ar: 'الحجرات' },
  { n: 50, name: 'Qaf', ayat: 45, ar: 'ق' },
  { n: 51, name: 'Adh-Dhariyat', ayat: 60, ar: 'الذاريات' },
  { n: 52, name: 'At-Tur', ayat: 49, ar: 'الطور' },
  { n: 53, name: 'An-Najm', ayat: 62, ar: 'النجم' },
  { n: 54, name: 'Al-Qamar', ayat: 55, ar: 'القمر' },
  { n: 55, name: 'Ar-Rahman', ayat: 78, ar: 'الرحمن' },
  { n: 56, name: "Al-Waqi'ah", ayat: 96, ar: 'الواقعة' },
  { n: 57, name: 'Al-Hadid', ayat: 29, ar: 'الحديد' },
  { n: 58, name: 'Al-Mujadila', ayat: 22, ar: 'المجادلة' },
  { n: 59, name: 'Al-Hashr', ayat: 24, ar: 'الحشر' },
  { n: 60, name: 'Al-Mumtahanah', ayat: 13, ar: 'الممتحنة' },
  { n: 61, name: 'As-Saff', ayat: 14, ar: 'الصف' },
  { n: 62, name: "Al-Jumu'ah", ayat: 11, ar: 'الجمعة' },
  { n: 63, name: 'Al-Munafiqun', ayat: 11, ar: 'المنافقون' },
  { n: 64, name: 'At-Taghabun', ayat: 18, ar: 'التغابن' },
  { n: 65, name: 'At-Talaq', ayat: 12, ar: 'الطلاق' },
  { n: 66, name: 'At-Tahrim', ayat: 12, ar: 'التحريم' },
  { n: 67, name: 'Al-Mulk', ayat: 30, ar: 'الملك' },
  { n: 68, name: 'Al-Qalam', ayat: 52, ar: 'القلم' },
  { n: 69, name: 'Al-Haqqah', ayat: 52, ar: 'الحاقة' },
  { n: 70, name: "Al-Ma'arij", ayat: 44, ar: 'المعارج' },
  { n: 71, name: 'Nuh', ayat: 28, ar: 'نوح' },
  { n: 72, name: 'Al-Jinn', ayat: 28, ar: 'الجن' },
  { n: 73, name: 'Al-Muzzammil', ayat: 20, ar: 'المزمل' },
  { n: 74, name: 'Al-Muddaththir', ayat: 56, ar: 'المدثر' },
  { n: 75, name: 'Al-Qiyamah', ayat: 40, ar: 'القيامة' },
  { n: 76, name: 'Al-Insan', ayat: 31, ar: 'الانسان' },
  { n: 77, name: 'Al-Mursalat', ayat: 50, ar: 'المرسلات' },
  { n: 78, name: 'An-Naba', ayat: 40, ar: 'النبإ' },
  { n: 79, name: "An-Nazi'at", ayat: 46, ar: 'النازعات' },
  { n: 80, name: "'Abasa", ayat: 42, ar: 'عبس' },
  { n: 81, name: 'At-Takwir', ayat: 29, ar: 'التكوير' },
  { n: 82, name: 'Al-Infitar', ayat: 19, ar: 'الإنفطار' },
  { n: 83, name: 'Al-Mutaffifin', ayat: 36, ar: 'المطففين' },
  { n: 84, name: 'Al-Inshiqaq', ayat: 25, ar: 'الإنشقاق' },
  { n: 85, name: 'Al-Buruj', ayat: 22, ar: 'البروج' },
  { n: 86, name: 'At-Tariq', ayat: 17, ar: 'الطارق' },
  { n: 87, name: "Al-A'la", ayat: 19, ar: 'الأعلى' },
  { n: 88, name: 'Al-Ghashiyah', ayat: 26, ar: 'الغاشية' },
  { n: 89, name: 'Al-Fajr', ayat: 30, ar: 'الفجر' },
  { n: 90, name: 'Al-Balad', ayat: 20, ar: 'البلد' },
  { n: 91, name: 'Ash-Shams', ayat: 15, ar: 'الشمس' },
  { n: 92, name: 'Al-Layl', ayat: 21, ar: 'الليل' },
  { n: 93, name: 'Ad-Duha', ayat: 11, ar: 'الضحى' },
  { n: 94, name: 'Ash-Sharh', ayat: 8, ar: 'الشرح' },
  { n: 95, name: 'At-Tin', ayat: 8, ar: 'التين' },
  { n: 96, name: "Al-'Alaq", ayat: 19, ar: 'العلق' },
  { n: 97, name: 'Al-Qadr', ayat: 5, ar: 'القدر' },
  { n: 98, name: 'Al-Bayyinah', ayat: 8, ar: 'البينة' },
  { n: 99, name: 'Az-Zalzalah', ayat: 8, ar: 'الزلزلة' },
  { n: 100, name: "Al-'Adiyat", ayat: 11, ar: 'العاديات' },
  { n: 101, name: "Al-Qari'ah", ayat: 11, ar: 'القارعة' },
  { n: 102, name: 'At-Takathur', ayat: 8, ar: 'التكاثر' },
  { n: 103, name: "Al-'Asr", ayat: 3, ar: 'العصر' },
  { n: 104, name: 'Al-Humazah', ayat: 9, ar: 'الهمزة' },
  { n: 105, name: 'Al-Fil', ayat: 5, ar: 'الفيل' },
  { n: 106, name: 'Quraysh', ayat: 4, ar: 'قريش' },
  { n: 107, name: "Al-Ma'un", ayat: 7, ar: 'الماعون' },
  { n: 108, name: 'Al-Kawthar', ayat: 3, ar: 'الكوثر' },
  { n: 109, name: 'Al-Kafirun', ayat: 6, ar: 'الكافرون' },
  { n: 110, name: 'An-Nasr', ayat: 3, ar: 'النصر' },
  { n: 111, name: 'Al-Masad', ayat: 5, ar: 'المسد' },
  { n: 112, name: 'Al-Ikhlas', ayat: 4, ar: 'الإخلاص' },
  { n: 113, name: 'Al-Falaq', ayat: 5, ar: 'الفلق' },
  { n: 114, name: 'An-Nas', ayat: 6, ar: 'الناس' },
];

export const surahByN = (n) => SURAHS.find((s) => s.n === Number(n)) || null;

// Anzahl Ayat in einem (Surah:Ayah)-Bereich (inklusive), auch über Surengrenzen.
export function ayahSpan(surahFrom, ayahFrom, surahTo, ayahTo) {
  const sf = Number(surahFrom);
  const st = Number(surahTo);
  const af = Number(ayahFrom);
  const at = Number(ayahTo);
  if (!surahByN(sf) || !surahByN(st)) return 0;
  if (sf > st || (sf === st && af > at)) return 0;
  if (sf === st) return at - af + 1;
  let total = surahByN(sf).ayat - af + 1; // Rest der Startsure
  for (let n = sf + 1; n < st; n++) total += surahByN(n).ayat; // volle Suren dazwischen
  total += at; // bis Ziel-Ayah in der Endsure
  return total;
}
